#!/bin/zsh
set -e
if [ ! -z ${APP_PORT+x} ]; then
  echo "APP_PORT is already set - aborting"
  echo "this should only be run in dev environment"
  exit 1
fi
./scripts/env
source .env-rolo
source .env-twix
# if 1st parameter is "pub" use the canonical URL
if [ "$1" = "pub" ]; then
  export APP_TEST_URL=${ROLO_URL_CANONICAL}
  export TWIX_TEST_URL=${TWIX_URL_ALT}
else
  export APP_TEST_URL=${APP_URL_ALT}
  export TWIX_TEST_URL=${TWIX_URL_ALT}
fi
npx ava dist/test/testE2E.js --serial
