#!/bin/zsh
set -e
if [[ -v APP_PORT ]]; then
  echo "APP_PORT is already set - aborting"
  echo "this should only be run in dev environment"
  exit 1
fi
./scripts/env
source .env
export APP_URL=${APP_URL_PROD}
npx ava --serial
