#!/bin/zsh
set -e
if [ ! -z ${APP_PORT+x} ]; then
  echo "APP_PORT is already set - aborting"
  echo "this should only be run in dev environment"
  exit 1
fi
./scripts/env
source .env-rolo
export APP_URL=${APP_URL_CANONICAL}
export APP_TEST_URL=${APP_URL_ALT}
npx ava dist/test/testApi.js --serial
