# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Test

on:
  push:
    branches:
    - main
    tags-ignore:
    - v*

env:
  APP_PORT: "${{ vars.APP_PORT }}"
  APP_URL: "${{ vars.APP_URL }}"
  APP_TEST_URL: "${{ vars.APP_URL }}"
  DATABASE_URL: "${{ vars.DATABASE_URL }}"
  DATABASE_NAME_LIVE: "${{ vars.DATABASE_NAME_LIVE }}"
  DATABASE_NAME_TEST: "${{ vars.DATABASE_NAME_TEST }}"
  COMMIT_HASH: ""
  BOOTSTRAP_SEED: "${{ secrets.BOOTSTRAP_SEED }}"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
        mongodb-version: ['6.0']
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.8.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
        mongodb-replica-set: rs0
    - name: Run E2E Tests
      uses: BerniWittmann/background-server-action@v1
      with:
        command: npm run test
        start: npm run start
        wait-on: '${{ vars.APP_URL }}'

