# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Test

on:
  push:
    branches:
      - main
    tags-ignore:
      - v*

env:
  # vars
  ROLO_PORT: "${{ vars.APP_PORT }}"
  DATABASE_URL: "${{ vars.DATABASE_URL }}"
  DATABASE_NAME_LIVE: "${{ vars.DATABASE_NAME_LIVE }}"
  DATABASE_NAME_TEST: "${{ vars.DATABASE_NAME_TEST }}"
  DATABASE_NAME_LOGS: "${{ vars.DATABASE_NAME_LOGS }}"
  TWIX_PORT: "${{ vars.TWIX_PORT }}"
  TWIX_URL: "${{ vars.TWIX_TEST_URL }}"
  ROLO_URL: "${{ vars.APP_TEST_URL }}"
  ROLO_URL_CANONICAL: "${{ vars.ROLO_URL_CANONICAL }}"
  # secrets
  BOOTSTRAP_SEED: "${{ secrets.BOOTSTRAP_SEED }}"
  ROLO_APIKEY_TEST: "${{ secrets.ROLO_APIKEY_TEST }}"
  ROLO_APIKEY_LIVE: ""
  PADDLE_CREDENTIALS: "${{ secrets.PADDLE_CREDENTIALS }}"
  TWIX_APIKEYS: "${{ secrets.LIZHI_APIKEYS }}"
  SMTP_CONFIG: "${{ secrets.SMTP_CONFIG }}"
  REPORTS_CONFIG: "${{ secrets.REPORTS_CONFIG }}"
  HMA_ROOT: "${{ secrets.HMA_ROOT }}"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
        mongodb-version: ["6.0", "7.0"]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run build
      - name: Run unit tests
        run: npm run test-unit
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
          mongodb-replica-set: rs0
      - name: Run E2E tests
        uses: BerniWittmann/background-server-action@v1
        with:
          command: npm run test-rolo && npm run test-twix
          start: npm run start-rolo & npm run start-twix
          wait-on: "${{ vars.APP_TEST_URL }}, ${{ vars.TWIX_TEST_URL }}"
