# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Test

on:
  push:
    branches:
      - main
    tags-ignore:
      - v*

env:
  # vars
  DATABASE_NAME: "${{ vars.DATABASE_NAME }}"
  DATABASE_URL: "${{ vars.DATABASE_URL }}"
  ROLO_PORT: "${{ vars.ROLO_PORT }}"
  ROLO_URL_CANONICAL: "${{ vars.ROLO_URL_CANONICAL }}"
  ROLO_URL: "${{ vars.ROLO_URL }}"
  TWIX_PORT: "${{ vars.TWIX_PORT }}"
  TWIX_URL: "${{ vars.TWIX_URL }}"
  # secrets
  BOOTSTRAP_SEED: "${{ secrets.BOOTSTRAP_SEED }}"
  ROLO_APIKEY_LIVE: ""
  ROLO_APIKEY_TEST: "${{ secrets.ROLO_APIKEY_TEST }}"
  ROLO_APIKEY_CONFIG: "${{ secrets.ROLO_APIKEY_CONFIG }}"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
        mongodb-version: ["6.0", "7.0"]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run build
      - name: Run unit tests
        run: npm run test-unit
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
          mongodb-replica-set: rs0
      - name: Run E2E tests
        uses: pilotmoon/background-server-action@v2
        with:
          command: npm run test-rolo && npm run test-twix
          start: npm run start-rolo & npm run start-twix
          wait-on: "${{ vars.ROLO_URL }}, ${{ vars.TWIX_URL }}"
