# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  APP_PORT: "${{ vars.APP_PORT }}"
  APP_URL: "${{ vars.APP_URL }}"
  DATABASE_URL: "${{ vars.DATABASE_URL }}"
  DATABASE_NAME_LIVE: "${{ vars.DATABASE_NAME_LIVE }}"
  DATABASE_NAME_TEST: "${{ vars.DATABASE_NAME_TEST }}"
  COMMIT_HASH: ""
  BOOTSTRAP_SEED: "${{ secrets.BOOTSTRAP_SEED }}"

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        # node-version: [16.x, 18.x]
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        mongodb-version: ['6.0']

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.8.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
        mongodb-replica-set: rs0
    - run: npm ci
    - run: npm run build
    - name: Run E2E Tests
      uses: BerniWittmann/background-server-action@v1
      with:
        command: npm run test
        start: npm run start
        wait-on: '${{ vars.APP_URL }}'
    - name: DigitalOcean App Platform deployment
      uses: digitalocean/app_action@main
      with:
        app_name: seal-app
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
